// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd8vcGJjBlQ1IMt0E7sHZBwzDKct_7hMU',
    appId: '1:1023772723142:web:6e6bab3a3aebadced254c7',
    messagingSenderId: '1023772723142',
    projectId: 'forexsignalpro-829b8',
    authDomain: 'forexsignalpro-829b8.firebaseapp.com',
    storageBucket: 'forexsignalpro-829b8.firebasestorage.app',
    measurementId: 'G-GYQK0BJWLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGY5YOjiVn44_irAaFfUcaHZ2yVsQzvws',
    appId: '1:1023772723142:android:7d3267011e837cadd254c7',
    messagingSenderId: '1023772723142',
    projectId: 'forexsignalpro-829b8',
    storageBucket: 'forexsignalpro-829b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcbR1mz6eP6L-khphynSJjqqAlU35xi5E',
    appId: '1:1023772723142:ios:da3987dce03871dcd254c7',
    messagingSenderId: '1023772723142',
    projectId: 'forexsignalpro-829b8',
    storageBucket: 'forexsignalpro-829b8.firebasestorage.app',
    iosClientId: '1023772723142-q54d0le316pr8goe12rto8l9ee6vt775.apps.googleusercontent.com',
    iosBundleId: 'com.liquidglass.app.liquidGlassOtpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcbR1mz6eP6L-khphynSJjqqAlU35xi5E',
    appId: '1:1023772723142:ios:da3987dce03871dcd254c7',
    messagingSenderId: '1023772723142',
    projectId: 'forexsignalpro-829b8',
    storageBucket: 'forexsignalpro-829b8.firebasestorage.app',
    iosClientId: '1023772723142-q54d0le316pr8goe12rto8l9ee6vt775.apps.googleusercontent.com',
    iosBundleId: 'com.liquidglass.app.liquidGlassOtpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd8vcGJjBlQ1IMt0E7sHZBwzDKct_7hMU',
    appId: '1:1023772723142:web:3b956e610f7c1a0ed254c7',
    messagingSenderId: '1023772723142',
    projectId: 'forexsignalpro-829b8',
    authDomain: 'forexsignalpro-829b8.firebaseapp.com',
    storageBucket: 'forexsignalpro-829b8.firebasestorage.app',
    measurementId: 'G-WBS2S2SRC8',
  );
}
